// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    About: typeof import('./src/views/About.vue')['default']
    AxiosSample: typeof import('./src/views/AxiosSample.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Footer: typeof import('./src/components/Footer.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/views/Home.vue')['default']
    I18nSample: typeof import('./src/views/I18nSample.vue')['default']
    IconifySample: typeof import('./src/views/IconifySample.vue')['default']
    IconSample: typeof import('./src/views/IconSample.vue')['default']
    IEpEdit: typeof import('~icons/ep/edit')['default']
    IEpHome: typeof import('~icons/ep/home')['default']
    IEpSearch: typeof import('~icons/ep/search')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TailwindSample: typeof import('./src/views/TailwindSample.vue')['default']
    UnoCssSample: typeof import('./src/views/UnoCssSample.vue')['default']
    VueUseSample: typeof import('./src/views/VueUseSample.vue')['default']
  }
}
